---
- name: Install docker dependencies
  ansible.builtin.apt:
   update_cache: true
   cache_valid_time: 3600
   state: present
   name:
    - apt-transport-https
    - ca-certificates
    - lsb-release

- name: Adding docker apt gpg key
  ansible.builtin.apt_key:
   url: https://download.docker.com/linux/debian/gpg
   state: present

- name: Adding deb docker repository
  ansible.builtin.apt_repository:
   repo: deb https://download.docker.com/linux/debian bullseye stable
   state: present

- name: Adding docker apt packages
  ansible.builtin.apt:
   update_cache: true
   cache_valid_time: 3600
   state: present
   name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-pip

- name: Upgrade pip
  ansible.builtin.pip:
   name: pip
   state: present
   extra_args: --upgrade
  vars:
   ansible_python_interpreter: /usr/bin/python3

- name: Install pip packages
  ansible.builtin.pip:
   name:
    - six
    - docker-compose
   state: present
  vars:
   ansible_python_interpreter: /usr/bin/python3

- name: Enable service and start docker
  ansible.builtin.service:
   name: docker
   enabled: true
   state: started
