---
# https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_server_module.html
- hosts: 127.0.0.1
  connection: local
  vars_files:
  -  "./vars/main.yml"
  tasks:
   - name: Install hetzner pip modules
     ansible.builtin.pip:
      name: hcloud
      state: present

   - name: remove Hetzner develop server
     hetzner.hcloud.hcloud_server:
      api_token: "{{ hetzner_cloud_api }}"
      name: "{{ hetzner_server_name }}"
      state: absent
